# Generated by Django 6.0 on 2026-02-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_add_paynow_reference_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='rides_payment_paynow_ref_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paynow_reference',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
