# Generated by Django 6.0 on 2026-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_payment_rides_payment_paynow_ref_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='special_instructions',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
