# Generated by Django 5.1.7 on 2026-02-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_payment_rides_payment_paynow_ref_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='flight_airline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='is_airport_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='passengers',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
