# Generated by Django 6.0 on 2026-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ridebooking_flight_airline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridebooking',
            old_name='flight_arrival_date',
            new_name='arrival_date',
        ),
        migrations.RenameField(
            model_name='ridebooking',
            old_name='flight_arrival_time',
            new_name='arrival_time',
        ),
        migrations.RenameField(
            model_name='ridebooking',
            old_name='is_airport_pickup',
            new_name='pickup_is_airport',
        ),
        migrations.RemoveField(
            model_name='ridebooking',
            name='flight_airline',
        ),
        migrations.RemoveField(
            model_name='ridebooking',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='ridebooking',
            name='passengers',
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='arrival_airline',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='arrival_flight_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='passenger_full_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='salutation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
