# Generated by Django 5.1.7 on 2026-03-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_add_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='payment_option',
            field=models.CharField(choices=[('POA', 'Pay on Arrival (Cash)'), ('pos_card', 'Pay on Arrival (POS/CARD)'), ('money_transfer', 'Money Transfer Agency'), ('paylink', 'Paylink'), ('PAYNOW', 'Pay Online (Paynow)')], max_length=16),
        ),
    ]
