# Generated by Django 5.1.7 on 2026-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_alter_ridebooking_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='baby_car_seater',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
