# Generated by Django 6.0 on 2026-05-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_sitesettings_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
