# Generated by Django 6.0 on 2026-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_alter_sitesettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='chauffeur_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='chauffeur_package_label',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='passengers_over_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='ride_type',
            field=models.CharField(choices=[('city', 'City Ride'), ('long_distance', 'Long Distance'), ('chauffeur', 'Chauffeur Drive')], default='city', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='chauffeur_packages',
            field=models.JSONField(default=list, help_text='List of chauffeur drive packages. Each entry must have: hours (int), price (decimal), km_limit (int), window_start ("HH:MM"), window_end ("HH:MM"), max_passengers (int).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_base_passengers',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_extra_pax_fee',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_free_luggage',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_luggage_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_per_km',
            field=models.DecimalField(decimal_places=2, default=1.4, max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='long_distance_threshold_km',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Trips at or beyond this distance (km) are treated as Long Distance', max_digits=6),
        ),
    ]
