# Generated by Django 6.0 on 2026-05-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_ridebooking_approximate_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='long_distance_extra_pax_fee',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
        ),
    ]
