# Generated by Django 6.0 on 2026-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0021_charge_hand_luggage_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='paylink_card_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ridebooking',
            name='paylink_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='money_transfer_recipient_name',
            field=models.CharField(default='Leonard Zambwi', help_text='Name the customer sends a money transfer to.', max_length=128),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='money_transfer_recipient_phone',
            field=models.CharField(default='+263772491982', help_text='Number the customer sends a money transfer to.', max_length=32),
        ),
    ]
