# Generated by Django 6.0 on 2026-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0023_drop_departure_terminals'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
