# Generated by Django 6.0 on 2026-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0024_ridebooking_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridebooking',
            name='other_luggage',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
