# Generated by Django 6.0 on 2026-09-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0025_ridebooking_other_luggage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='pricing_baby_seat_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
